//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.Cart_Itemes = new HashSet<Cart_Itemes>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Uid { get; set; }
    
        public virtual ICollection<Cart_Itemes> Cart_Itemes { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
