//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Itemes
    {
        public int Cid { get; set; }
        public int Pid { get; set; }
        public int Qty { get; set; }
        public decimal ItemPrice { get; set; }
        public int Id { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
