//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Uid { get; set; }
        public int Cid { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual User User { get; set; }
    }
}
