//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Enrolls = new HashSet<Enroll>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OfferdBy { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Enroll> Enrolls { get; set; }
    }
}
