//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartMidTask2.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
